### ISSUE TITLE
header size exceeds limit '8192' bytes

### ISSUE THREAD

**Issue by nhuydev1704** [mufeng889/react-soybean-admin#10]
### Software Version

1.0.0-beta.1

### Operating Environment

MacOS

### Operating Architecture

None

### Reproduce Steps

Login

### What is the expected result?

Login success

### What is the actual result?

header size exceeds limit '8192' bytes

![Screenshot 2024-09-28 at 22 52 26](https://github.com/user-attachments/assets/85ed1ea3-86b7-47f3-876a-9198705d8ccf)

**Comment by mufeng889** [comment]
It's likely that the server address of this network interface is located in China, which is why you are experiencing a timeout there.

**Comment by mufeng889** [comment]
And don't forget, brothers, to give  a star  thank u！
