### ISSUE TITLE
[功能]: 作者能不能出一个没有国际化的版本？

### ISSUE THREAD

**Issue by gulinb666** [mufeng889/react-soybean-admin#12]
### 描述

作者能不能出一个没有国际化的版本？我不需要国际化改代码改起来非常不好改

### 建议的解决方案

作者能不能出一个没有国际化的版本？我不需要国际化改代码改起来非常不好改

**Comment by mufeng889** [comment]
作者 很忙 不过考虑可以出一个vite插件 去完成这个事情  不过时间要很长  因为未来很长一段时间我都很忙  暂时没空  建议加入qq群或者微信群 去询问群主 他有更好的办法 不用改很多东西

**Comment by gulinb666** [comment]
好的，谢谢作者大大，看好你们哦😄
