### ISSUE TITLE
[功能]: 打开多个tab时，没有缓存状态，而这个功能是非常刚需的

### ISSUE THREAD

**Issue by jwki18n** [mufeng889/react-soybean-admin#13]
### 描述

打开多个tab时，没有缓存状态，而这个功能是非常刚需的

### 建议的解决方案

打开多个tab时，没有缓存状态，而这个功能是非常刚需的

**Comment by mufeng889** [comment]
你自己好好看看文档怎么开启  缓存  是需要自己手动开启的  这个实例标签页 和用户管理开启  了  好好看看再说
