### ISSUE TITLE
[功能]: 样式建议

### ISSUE THREAD

**Issue by liao1714** [mufeng889/react-soybean-admin#15]
### 描述

当前主题配置有标签高度，页脚高度，侧标栏宽度等配置，如果调整太过就会导致样式不够美观

### 建议的解决方案

选取一个区间值更好的限制来达到美观要求

### 额外的上下文

另外，希望出一个锁定页面功能

**Comment by mufeng889** [comment]
没有必要  用户自己设置 我们没有必要强硬设置区间  给用户带来不好的体验
