### ISSUE TITLE
[Bug]: 登录页面，刷新控制台报错，再次刷新处于加载状态

### ISSUE THREAD

**Issue by Howie7793** [mufeng889/react-soybean-admin#8]
### 软件版本

node18

### 运行环境

MacOS

### 运行架构

ARM [64] (别名：AArch64 / ARMv8）

### 重现步骤

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/82447ab7-f7f9-491a-a313-3eb024127c1a">
 登录页面，刷新控制台报错，再次刷新处于加载状态

### 期望的结果是什么？

登录页面刷新正常

### 实际的结果是什么？

 登录页面，刷新控制台报错，再次刷新处于加载状态

**Comment by mufeng889** [comment]
谢谢你提供的bug 能帮我点个star吗  就剩这一点就能更到1.0beat了

**Comment by Howie7793** [comment]
嗯嗯，点了，感谢开源
