### ISSUE TITLE
[Bug]: 链接无法访问

### ISSUE THREAD

**Issue by southliu** [mufeng889/react-soybean-admin#9]
### 软件版本

1

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

![image](https://github.com/user-attachments/assets/9a73148a-7f48-4d75-aff7-b691292e688e)
[react-soybean.ohh-889.com](https://react-soybean.ohh-889.com/)这个链接进不去

### 期望的结果是什么？

进的去

### 实际的结果是什么？

进不去

**Comment by mufeng889** [comment]
你要开 科学上网  没开的话 访问这个https://react-soybean-admin.pages.dev/ 顺便帮忙点点star 谢谢

**Comment by southliu** [comment]
star了，后续考虑开发keepalive的功能吗？

**Comment by mufeng889** [comment]
考虑 但是暂时没有发现  可以适配的  市面上的插件    我的路由是react-router官方最新的数据路由器  和市面上的缓存插件不兼容  但是我突然想到umi好像也是 数据路由器 10.1有空的话会去看一下umi怎么实现的  如果仍然不兼容将不考虑实现了 正式升级为1.0版本了

**Comment by southliu** [comment]
我目前采用react-activation库实现了， 不过有个问题就是你主题变化有点问题，会出现切换黑暗模式，按钮已经变化颜色，表格没有变化的情况。

**Comment by mufeng889** [comment]
失敬失敬 ， 我刚才看了一下你的作品 我们的路由 不是同一种方式实现的  而我不可能用你的那种方式 实现  我目前实现路由的方式是对数据路由器  做了扩展  添加了一些api 和 全局前置守卫 和后置守卫 这也是我这个框架的亮点  不会抛弃现有实现的 数据路由器的

**Comment by mufeng889** [comment]
我目前的路由实现方式无法兼容 react-activation这个库

**Comment by mufeng889** [comment]
至于切换 暗黑模式 的问题 应该是动画吧

**Comment by southliu** [comment]
似乎不是动画问题，我理解是dom被react-activation缓存了，切换antd的主题没有触发缓存的dom进行变化，如果去除react-activation就正常。
tql，我还在研究路由守卫的实现👍

**Comment by mufeng889** [comment]
你可以 提供一张图片    我没有实现缓存 我没有遇到你说的问题

**Comment by mufeng889** [comment]
去看 react-router的源码 去找最新数据路由器的实现方式  东西不是太多 不对它进行修改而是扩展 并不是很难

**Comment by southliu** [comment]
🉑我有空看看源码，主题切换问题可以慢慢解决，问题不大。
